# Generated by Django 3.2.9 on 2021-11-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking_1',
            fields=[
                ('ParkingId', models.AutoField(primary_key=True, serialize=False)),
                ('BookingDate', models.DateField()),
                ('TimeOfBooking', models.DateField()),
                ('DriverName', models.CharField(max_length=200)),
                ('LicensePlate', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Parking_2',
            fields=[
                ('ParkingId', models.AutoField(primary_key=True, serialize=False)),
                ('BookingDate', models.DateField()),
                ('TimeOfBooking', models.DateField()),
                ('DriverName', models.CharField(max_length=200)),
                ('LicensePlate', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Parking_3',
            fields=[
                ('ParkingId', models.AutoField(primary_key=True, serialize=False)),
                ('BookingDate', models.DateField()),
                ('TimeOfBooking', models.DateField()),
                ('DriverName', models.CharField(max_length=200)),
                ('LicensePlate', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Parking_4',
            fields=[
                ('ParkingId', models.AutoField(primary_key=True, serialize=False)),
                ('BookingDate', models.DateField()),
                ('TimeOfBooking', models.DateField()),
                ('DriverName', models.CharField(max_length=200)),
                ('LicensePlate', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('ParkingId', models.AutoField(primary_key=True, serialize=False)),
                ('BookingDate', models.DateField()),
                ('Lot_1', models.BooleanField(default=True)),
                ('Lot_2', models.BooleanField(default=True)),
                ('Lot_3', models.BooleanField(default=True)),
                ('Lot_4', models.BooleanField(default=True)),
            ],
        ),
    ]
