# Generated by Django 3.2.9 on 2021-11-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking_1',
            name='TimeOfBooking',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='parking_2',
            name='TimeOfBooking',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='parking_3',
            name='TimeOfBooking',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='parking_4',
            name='TimeOfBooking',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='Lot_1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='Lot_2',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='Lot_3',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='Lot_4',
            field=models.CharField(max_length=200),
        ),
    ]
